trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: taskapp-variables

steps:

# Login to Azure Container Registry
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'acrtaskappashir'

# Build and Push Backend Docker Image
- task: Docker@2
  displayName: Build and Push Backend Image
  inputs:
    command: buildAndPush
    repository: 'backend'
    dockerfile: 'backend/Dockerfile'
    buildContext: 'backend'
    containerRegistry: 'acrtaskappashir'
    tags: |
      latest

# Deploy Backend Container to Azure App Service
- task: AzureWebAppContainer@1
  displayName: Deploy Backend App
  inputs:
    azureSubscription: 'azure-service-connection'
    appName: 'app-taskapp-backend-f3hkeedxdzawc4fm'
    containers: 'acrtaskappashir.azurecr.io/backend:latest'